name: limousine
description: "Desktop app for managing web dev environments"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  xterm: ^4.0.0
  flutter_pty: ^0.4.2
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  path: ^1.9.1
  logging: ^1.3.0
  google_fonts: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

fonts:
   - family: Cascadia Mono
     fonts:
       - asset: fonts/CascadiaMonoPL.ttf
